######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 21 00:55:59 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
#CONFIG += debug
CONFIG += console
QT = core

# Input

include(../../src/netflixresultsgenerator.pri)

SOURCES += main.cpp
